import type { Metadata } from "next";
import Navbar from "./components/Navbar/Navbar";
import "bootstrap/dist/css/bootstrap.min.css";
import "react-toastify/dist/ReactToastify.css";
import BootstrapClient from "./components/BootstrapClient";
import { ReactQueryClientProvider } from "./components/ReactQueryClient";
import { ToastContainer } from "react-toastify";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body>
        <ReactQueryClientProvider>
          <Navbar />
          {children}
          <ToastContainer />
          <BootstrapClient />
        </ReactQueryClientProvider>
      </body>
    </html>
  );
}
