@hostname = http://localhost:5001

GET {{hostname}}/v1/products
content-type: application/json

###

GET {{hostname}}/v1/products/0

###

POST {{hostname}}/v1/products
content-type: application/json

{
    "name": "cadeira",
    "price": 100,
    "stock": 10
}

###

PUT {{hostname}}/v1/products/0
content-type: application/json

{
    "name": "mesa",
    "price": 200,
    "stock": 20
}

###

DELETE {{hostname}}/v1/products/0

###