FROM ubuntu:latest

RUN apt-get update
RUN apt-get install -y nginx

ARG PORTA_ARG
ENV PORTA=${PORTA_ARG}

EXPOSE ${PORTA_ARG}

CMD ["nginx", "-g", "daemon off;"]

# comandos executados
# docker build -t mapeando-portas --build-arg PORTA_ARG=7000 .
# docker run -d --name exercicio-1 -p 8000:7000 mapeando-portas