services:
  bdcontainer:
    container_name: bdcontainer
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=pass2025
    volumes:
      - volume_db:/var/lib/mysql
    networks:
      - rede_bd

  dbguicontainer:
    container_name: dbguicontainer
    image: phpmyadmin:latest
    ports:
      - 8080:80
    environment:
      - PMA_HOST=bdcontainer
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=pass2025
    depends_on:
      - bdcontainer
    networks:
      - rede_bd

networks:
  rede_bd:
    driver: bridge

volumes:
  volume_db:
